export const ADD_FETCHED_TODOS = 'ADD_FETCHED_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS'

export const RESET_TODOS = 'RESET_TODOS'
export const SET_ERROR = 'TODOS_ERROR'